services:
  db:
    image: postgres:17
    container_name: ilocano_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    container_name: ilocano_backend
    build:
      context: ./ilocanobackend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DJANGO_KEY=${DJANGO_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    env_file:
      - .env
    volumes:
      - ./ilocano_backend:/app/backend
    command: bash -c "sleep 10 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
volumes:
  postgres_data:
    driver: local
