version: '3.7'

services:
  reverse_proxy:
    container_name: ilocano-backend-nginx
    build: ./ilocano-backend-nginx
    volumes:
      - ./ilocano-backend-nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:  
      - 80:80
    depends_on:
      - ilocano-backend
      - user-login
  ilocano-backend:
    tty: true
    container_name: ilocano-backend
    build: ./ilocano-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ilocano-backend:/code
    ports:
      - 8000:8000
    # expose:
    #   - "8000"
  user-login:
    tty: true
    container_name: user-login
    build: ./user-login
    command: yarn start
    ports:
      - 3000:3000
    # expose:
    #   - "3000"
    image: no-react
    volumes:
      - ./user-login:/code