version: "3.7"

services:
  reverse_proxy:
    container_name: lets-speak-backend-nginx
    build: ./lets-speak-backend-nginx
    volumes:
      - ./lets-speak-backend-nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - lets-speak-backend
      - user-authentication
  lets-speak-backend:
    tty: true
    container_name: lets-speak-backend
    build: ./lets-speak-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./lets-speak-backend:/code
    ports:
      - 8000:8000
    expose:
      - "8000"
  user-authentication:
    tty: true
    container_name: user-authentication
    build: ./user-authentication
    command: yarn dev
    ports:
      - 3000:3000
    expose:
      - "3000"
    image: no-react
    volumes:
      - ./user-authentication:/code
