# Generated by Django 4.1.6 on 2023-03-02 17:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('english', models.CharField(max_length=30)),
                ('ilokano', models.CharField(max_length=20)),
                ('variations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('lesson_number', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
    ]
