# Generated by Django 4.1.6 on 2023-03-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbankdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbank',
            name='lesson_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
