# Generated by Django 4.1.6 on 2023-02-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('pronunciation', models.CharField(max_length=30)),
                ('translation', models.CharField(max_length=20)),
            ],
        ),
    ]
