# Generated by Django 4.1.6 on 2023-02-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbankdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='lesson_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
