# Generated by Django 4.1.6 on 2023-02-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbankdb', '0002_word_lesson_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='WordBank',
        ),
    ]
