# Generated by Django 5.2 on 2025-06-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilocano', models.CharField(max_length=255, unique=True)),
                ('english', models.TextField()),
                ('part_of_speech', models.CharField(blank=True, max_length=50, null=True)),
                ('example_sentence', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
