# Generated by Django 4.1.6 on 2023-07-16 22:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilocano', models.CharField(max_length=20)),
                ('english', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('variations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('lesson_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words_for_lesson', to='ilocanodb.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('I. Dialog', 'Dialog'), ('II. Translating the Dialog', 'Translating the Dialog'), ('III. Learning the Dialog', 'Learning the Dialog'), ('IV. Role-Playing', 'Role-Playing'), ('V. Vocabulary', 'Vocabulary'), ('VI. Changing the Dialog', 'Changing the Dialog'), ('VII. Question and Answer', 'Question and Answer'), ('VIII. Notes', 'Notes'), ('IX. Exercises', 'Exercises'), ('X. Communication Activity', 'Communication Activity'), ('XI. Writing Practice', 'Writing Practice'), ('XII. Listening Practice', 'Listening Practice')], default='I. Dialog', max_length=30)),
                ('description', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ilocanodb.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('lesson_number', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='ilocanodb.lesson')),
            ],
        ),
    ]
