# Generated by Django 4.1.6 on 2023-05-18 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilocanodb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ilocanodb.lesson'),
        ),
    ]
